- name: Create Jenkins Folders
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item}}"
    password: admin
    user: admin
    url: http://jenkins.example.com:8080
  loop: "{{folders}}"

- name: Create Pipeline Jobs
  include_role:
    name: jenkins-jobs
    tasks_from: pipeline-job
  loop: "{{pipeline_jobs}}"

- name: Create Multi Pipeline Jobs
  include_role:
    name: jenkins-jobs
    tasks_from: multibranch
  loop: "{{multibranch_jobs}}"
