- name: Create Template file
  template:
    src: pipeline-job.xml
    dest: /tmp

- name: Check if Job Exists
  community.general.jenkins_job_info:
    name: "{{item.folderName}}/{{item.jobName}}"
    user: admin
    password: admin
    url: http://jenkins.example.com:8080
  register: job_info
  ignore_errors: yes

- name: Create Jenkins Jobs
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/pipeline-job.xml') }}"
    name: "{{item.folderName}}/{{item.jobName}}"
    password: admin
    user: admin
    url: http://jenkins.example.com:8080
  when: job_info.failed

